const constants = {
  LOG_IN: "LOG_IN",
  SET_RESOPT: "SET_RESOPT", // Waste processor options set


  FETCH_ITEMS_REQUEST: 'FETCH_ITEMS_REQUEST',
  RECEIVE_ITEMS: "RECEIVE_ITEMS",
  FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE'

  //SET_RLI: "SET_RLI",
  //FETCH_RESERVATION_LIST_ITEMS: "FETCH_RESERVATION_LIST_ITEMS",
  //CANCEL_RESLIST_FETCH: "CANCEL_RESLIST_FETCH",
  //UPDATE_RESLIST: "UPDATE_RESLIST"
  //ADD_REQUEST: "ADD_REQUEST"
}

export default constants
