const constants = {
  LOG_IN: "LOG_IN",
  SET_RESOPT: "SET_RESOPT", // Waste processor options set

  SET_CATEGORIES: "SET_CATEGORIES",
  SET_SUB_CATEGORIES: "SET_SUB_CATEGORIES",

  SET_RLI: "SET_RLI",
  FETCH_RESERVATION_LIST_ITEMS: "FETCH_RESERVATION_LIST_ITEMS",

  SET_NOTIF:"SET_NOTIF"
  //CANCEL_RESLIST_FETCH: "CANCEL_RESLIST_FETCH",
  //UPDATE_RESLIST: "UPDATE_RESLIST"
  //ADD_REQUEST: "ADD_REQUEST"
}

export default constants
