const constants = {
  LOG_IN: "LOG_IN",
  SET_RESOPT: "SET_RESOPT",
  SET_RLI: "SET_RLI",
  FETCH_RESERVATION_LIST_ITEMS: "FETCH_RESERVATION_LIST_ITEMS"
  //ADD_REQUEST: "ADD_REQUEST"
}

export default constants
